# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.centralwidget_2.setGeometry(QtCore.QRect(0, 10, 771, 533))
        self.centralwidget_2.setObjectName("centralwidget_2")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget_2)
        self.btn_encrypt.setGeometry(QtCore.QRect(190, 460, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget_2)
        self.btn_decrypt.setGeometry(QtCore.QRect(590, 460, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.label = QtWidgets.QLabel(self.centralwidget_2)
        self.label.setGeometry(QtCore.QRect(50, 130, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget_2)
        self.label_2.setGeometry(QtCore.QRect(40, 230, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget_2)
        self.label_3.setGeometry(QtCore.QRect(40, 330, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget_2)
        self.label_4.setGeometry(QtCore.QRect(350, 50, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget_2)
        self.txt_plain_text.setGeometry(QtCore.QRect(140, 120, 591, 71))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget_2)
        self.txt_cipher_text.setGeometry(QtCore.QRect(140, 330, 591, 71))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.key = QtWidgets.QTextEdit(self.centralwidget_2)
        self.key.setGeometry(QtCore.QRect(140, 220, 591, 51))
        self.key.setObjectName("key")
        self.statusbar_2 = QtWidgets.QStatusBar(self.centralwidget)
        self.statusbar_2.setGeometry(QtCore.QRect(330, 310, 3, 18))
        self.statusbar_2.setObjectName("statusbar_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label.setText(_translate("MainWindow", "plain text"))
        self.label_2.setText(_translate("MainWindow", "key"))
        self.label_3.setText(_translate("MainWindow", "ciphertext"))
        self.label_4.setText(_translate("MainWindow", "railfence CIPHER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
