# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.centralwidget_2.setGeometry(QtCore.QRect(-30, -10, 841, 573))
        self.centralwidget_2.setObjectName("centralwidget_2")
        self.centralwidget_3 = QtWidgets.QWidget(self.centralwidget_2)
        self.centralwidget_3.setGeometry(QtCore.QRect(30, 20, 781, 533))
        self.centralwidget_3.setObjectName("centralwidget_3")
        self.btn_encrypt_3 = QtWidgets.QPushButton(self.centralwidget_3)
        self.btn_encrypt_3.setGeometry(QtCore.QRect(190, 460, 75, 23))
        self.btn_encrypt_3.setObjectName("btn_encrypt_3")
        self.btn_decrypt_3 = QtWidgets.QPushButton(self.centralwidget_3)
        self.btn_decrypt_3.setGeometry(QtCore.QRect(590, 460, 75, 23))
        self.btn_decrypt_3.setObjectName("btn_decrypt_3")
        self.label_plain_3 = QtWidgets.QLabel(self.centralwidget_3)
        self.label_plain_3.setGeometry(QtCore.QRect(50, 130, 100, 13))
        self.label_plain_3.setObjectName("label_plain_3")
        self.label_key_3 = QtWidgets.QLabel(self.centralwidget_3)
        self.label_key_3.setGeometry(QtCore.QRect(50, 230, 100, 13))
        self.label_key_3.setObjectName("label_key_3")
        self.label_cipher_3 = QtWidgets.QLabel(self.centralwidget_3)
        self.label_cipher_3.setGeometry(QtCore.QRect(50, 330, 100, 13))
        self.label_cipher_3.setObjectName("label_cipher_3")
        self.label_title_3 = QtWidgets.QLabel(self.centralwidget_3)
        self.label_title_3.setGeometry(QtCore.QRect(300, 50, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_3.setFont(font)
        self.label_title_3.setObjectName("label_title_3")
        self.txt_plain_text_3 = QtWidgets.QTextEdit(self.centralwidget_3)
        self.txt_plain_text_3.setGeometry(QtCore.QRect(140, 120, 591, 71))
        self.txt_plain_text_3.setObjectName("txt_plain_text_3")
        self.txt_key_3 = QtWidgets.QTextEdit(self.centralwidget_3)
        self.txt_key_3.setGeometry(QtCore.QRect(140, 220, 591, 51))
        self.txt_key_3.setObjectName("txt_key_3")
        self.txt_cipher_text_3 = QtWidgets.QTextEdit(self.centralwidget_3)
        self.txt_cipher_text_3.setGeometry(QtCore.QRect(140, 330, 591, 71))
        self.txt_cipher_text_3.setObjectName("txt_cipher_text_3")
        self.statusbar_2 = QtWidgets.QStatusBar(self.centralwidget_2)
        self.statusbar_2.setGeometry(QtCore.QRect(340, 150, 3, 18))
        self.statusbar_2.setObjectName("statusbar_2")
        self.menubar_2 = QtWidgets.QMenuBar(self.centralwidget)
        self.menubar_2.setGeometry(QtCore.QRect(-30, -10, 864, 21))
        self.menubar_2.setObjectName("menubar_2")
        self.statusbar_3 = QtWidgets.QStatusBar(self.centralwidget)
        self.statusbar_3.setGeometry(QtCore.QRect(-30, -10, 3, 18))
        self.statusbar_3.setObjectName("statusbar_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_encrypt_3.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt_3.setText(_translate("MainWindow", "Decrypt"))
        self.label_plain_3.setText(_translate("MainWindow", "Plain Text"))
        self.label_key_3.setText(_translate("MainWindow", "Key"))
        self.label_cipher_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label_title_3.setText(_translate("MainWindow", "VIGENERE CIPHER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
